name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          pip install black sphinx pytest pytest-cov flake8
          pip install -r docs/requirements.txt
          sudo apt-get install pandoc

      - name: Black
        run: |
          black --version
          black --check .

      - name: Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Tests
        run: |
          echo '${{ secrets.ECMWFAPIRC }}' > ~/.ecmwfapirc
          echo '${{ secrets.CDSAPIRC }}' > ~/.cdsapirc
          echo '${{ secrets.TEST }}' > ~/.test
          echo '========'
          cat ~/.test
          echo '========'
          python setup.py develop
          pytest

      - name: Documentation
        run: |
          make clean
          make html
          # make linkcheck (don't run yet)
        working-directory: docs
