name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          pip install black sphinx pytest
          pip install -r docs/requirements.txt
          sudo apt-get install pandoc

      - name: Black
        run: |
          black --version
          black --check .

      - name: Documentation
        run: |
          make clean
          make html
          # make linkcheck (don't run yet)
        working-directory: docs

      - name: Tests
        run: |
          pytest
